### PR TITLE
Filter out null values in toArray/getJSON

### PR DESCRIPTION
**Pull request by sandcore-dev**
Hi,

I've added a new helper method for removing all the unnecessary `null` values in the JSON output.
I've also added a test for it.

Noticed just now that I inadvertently changed whitespaces in `SerializationHelperTest`, sorry for that.

### CODE REVIEW

**Comment by Sibyx** [comment]
@sandcore-dev Hi buddy, would you like to check it out?

**Comment by sandcore-dev** [comment]
Yeah sorry, I have been busy lately. I will fix the tests, hopefully soon.

**Comment by sandcore-dev** [comment]
I wanted to start on fixing the tests, but I noticed that tests on the master branch are failing too. One is relatively minor, a year was omitted in the copyright. The other one may be more serious: all 'unsupported' keys get a colon appended. Looking at the code, I'm not sure that is correct behavior. Looks like it should omit the colon when there is no namespace.

Can someone fix this so I can actually fix the unit test errors caused by my own code changes?

**Comment by Sibyx** [comment]
@sandcore-dev Hi, long time no see (I am sorry), tests are fixed, please check if everything is ready for merge. `1.0` will be released after merging. I want to perform some more radical refactoring (and a lot of bug fixing) in 2.x

**Comment by sandcore-dev** [comment]
There you go.

**Pull request merged**
