### PR TITLE
Stats: add elevationLoss // add simple smoothing algorithm

### PR DESCRIPTION
**Pull request by lukey78**
This pull request extends my previous one.

1) add elevationLoss to the Stats object -- this one is equally important as elevationGain, in my opinion.

2) calculation of elevation gain/loss is difficult and is done differently by most vendors -- that's why the same GPS track results in different stats on each platform. All products usually apply a smoothing function to filter out GPS differences adding up to huge amounts. A good abstract about this problem can be found [here](http://www.gpsvisualizer.com/tutorials/elevation_gain.html).

I've added a simple configurable smoothing algorithm considering only height and distance differences between points if they exceed a specific factor (e.g. 2 meters).

I've tested several mountaineering routes and compared the results to the ones Suunto displays on their website. With a factor of 2 for each it works quite well.

I'm not sure about the docs. The MDs in the docs folder seem to be auto-generated. Actually I don't think these are needed. The library is not that big and one README with examples and configuration options should be enough.

### CODE REVIEW

**Comment by Sibyx** [comment]
For code style fixies you should use [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer). Configuration is already part of the repo.

**Comment by Sibyx** [comment]
Thank you for many interesting features :)

I want to get rid of the auto-generated documentation ASAP, but last few months I am quite busy. Nice README file with examples is enough I guess.

Feel free to add yourself to the contributor's list, I will merge your branch in the evening (I am from Slovakia so at 11pm CEST)

**Comment by lukey78** [comment]
I refactored the elevation gain/loss and distance calculation to separate classes to make the code a bit more readable and reusable. The calculation is now done for Routes and Segments. Tracks add up just the segment stats.

I think it's ready for merging now. Thanks for the great library!

**Comment by Sibyx** [comment]
Hi, so thank you very much for the PR :)  Merging and I will prepare release this weekend.

**Pull request merged**
